import type { Market, Trade, Position } from "./types";

export const mockTrades: Trade[] = [
  {
    id: "1",
    marketQuestion: "Will the Ethereum ETF be approved by May 31, 2024?",
    marketCategory: "Crypto",
    entryPrice: 0.65,
    size: 1000,
    pnl: 350,
    outcome: "win",
    thesis: "Positive sentiment from regulators and insider reports suggest a high probability of approval, creating a favorable risk/reward scenario.",
    date: "2024-05-15T10:00:00Z",
    conviction: 4,
    holdDurationHours: 120,
  },
  {
    id: "2",
    marketQuestion: "Will 'Civil War' gross over $100M domestically by June 1?",
    marketCategory: "Entertainment",
    entryPrice: 0.40,
    size: 500,
    pnl: -200,
    outcome: "loss",
    thesis: "A24's strong marketing push and the film's controversial subject matter were expected to drive ticket sales, but it faced stronger than expected competition.",
    date: "2024-05-20T14:30:00Z",
    conviction: 3,
    holdDurationHours: 240,
  },
  {
    id: "3",
    marketQuestion: "Will the Fed cut interest rates in Q2 2024?",
    marketCategory: "Finance",
    entryPrice: 0.80,
    size: 2000,
    pnl: -1600,
    outcome: "loss",
    thesis: "Persistent inflation indicators were underestimated. The market had priced in a cut too early, I believed the Fed would act to stimulate markets pre-election.",
    date: "2024-06-01T11:00:00Z",
    conviction: 5,
    holdDurationHours: 72,
  },
  {
    id: "4",
    marketQuestion: "Will a new AI model with over 5 trillion parameters be announced by a major lab by July 1?",
    marketCategory: "Technology",
    entryPrice: 0.25,
    size: 800,
    pnl: 600,
    outcome: "win",
    thesis: "The competitive pace of AI development and recent hardware advancements made a surprise announcement likely, despite no official roadmaps.",
    date: "2024-06-10T09:00:00Z",
    conviction: 2,
    holdDurationHours: 480,
  },
  {
    id: "5",
    marketQuestion: "Will global temperatures in July 2024 exceed the record set in July 2023?",
    marketCategory: "Science",
    entryPrice: 0.70,
    size: 1500,
    pnl: 0,
    outcome: "pending",
    thesis: "Ongoing El Niño effects combined with baseline warming trends make it highly probable that we will see another record-breaking month.",
    date: "2024-07-01T08:00:00Z",
    conviction: 4,
    holdDurationHours: 0,
  },
];
